## 00. Pytorch fundamentals

In [ ]:
!nvidia-smi

Wed Dec 17 17:13:13 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   49C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Creating tensors


In [ ]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector

vector = torch.tensor([7,7])
vector
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

###Random tensors

In [18]:
#create rand tensor of size
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4878, 0.8911, 0.6094, 0.8462],
        [0.1829, 0.0370, 0.0984, 0.5932],
        [0.0615, 0.5930, 0.5268, 0.0413]])

In [ ]:
#create random tensor similiar to image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height , width, color chanel
random_image_size_tensor.shape
random_image_size_tensor

### Zeros and ones

In [3]:
# create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
#use torch.range
one_to_ten = torch.arange(start=0,end=1000, step= 100)


In [9]:
#create tnesors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [4]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)

float_32_tensor

tensor([3., 6., 9.])

In [12]:
float_32_tensor.dtype

torch.float32

### getting info from tensors - attributes

1. Tensors not right datatype - get type tensor.dtype
2. Tensors not right shape - get shape tensor.shape
3. Tensors not on the right device - get device tensor.device

In [5]:
# create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1136, 0.0474, 0.8147, 0.2796],
        [0.3177, 0.9306, 0.7029, 0.7394],
        [0.5301, 0.6684, 0.6373, 0.3229]])

In [8]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"SHape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1136, 0.0474, 0.8147, 0.2796],
        [0.3177, 0.9306, 0.7029, 0.7394],
        [0.5301, 0.6684, 0.6373, 0.3229]])
Datatype of tensor: torch.float32
SHape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors - operations

operations include:
 * addition
 * subtraction
 * multiplicaiton
 * division
 * matrix multiplication


In [6]:
# create a tensor add 10 to it

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [7]:
#multiply bty 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

### Matrix multiplication

two main ways of performing multiplication in NN and dp
1. Element wise
2. matrix multiplication - dot product

In [9]:
#Element wise
tensor
tensor * tensor

tensor([100, 400, 900])

In [10]:
#matrix
torch.matmul(tensor,tensor)

tensor(1400)

### One of the most common errors - shape errors
to fix errors just transpose the matrix


In [7]:
tensorB = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensorB

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [8]:
tensorB.T

tensor([[1, 3, 5],
        [2, 4, 6]])

### finding max,min,mean,sum etc

In [2]:
x = torch.arange(0,100,20)
x

tensor([ 0, 20, 40, 60, 80])

In [3]:
torch.min(x)
torch.max(x)
torch.mean(x.type(torch.float32))
torch.sum(x)

tensor(200)

In [4]:
#find position of min or max
x.argmin()

tensor(0)

## Reshaping, stacking, squeezing, and un squeezing

In [5]:
import torch
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
#add a extra dimension
x_reshape = x.reshape(3,3)
x_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [9]:
#change the view
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [11]:
#stack tensors on top
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

## Indexing

In [12]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
x[0][0]

tensor([1, 2, 3])

In [17]:
x[0][0][0]

tensor(1)

## pytorch and numpy

In [19]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Reproducibility
concept of a random seed to introduce more randomness

In [20]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1909, 0.9290, 0.0785, 0.6172],
        [0.9346, 0.6337, 0.3712, 0.9915],
        [0.6277, 0.5301, 0.3663, 0.0135]])
tensor([[0.9086, 0.4576, 0.7641, 0.6332],
        [0.7068, 0.5676, 0.0373, 0.6586],
        [0.1541, 0.5586, 0.5788, 0.4267]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [22]:
#make some random but reproducible tensors
import torch
torch.manual_seed(42)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(42)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch on GPUs

gpus = faster computations

### 1. getting a gpu

1. easiest - using google colab
2. using your own gpu
3. use cloud computing
